### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by solarhell** [guoc/nearbt#1]
....../NearBT/ViewController.swift:10:8: No such module 'OneTimePassword'

**Comment by guoc** [comment]
[Carthage](https://github.com/Carthage/Carthage) is required to compile OneTimePassword.
With Carthage installed, `carthage update` could make this.

I just added the compiled OneTimePassword framework in the [release](https://github.com/guoc/nearbt/releases/tag/v0.1). Please use [NearBT-iOS-v0.1.zip](https://github.com/guoc/nearbt/releases/download/v0.1/NearBT-iOS-v0.1.zip).
